### ISSUE TITLE
How did you extract the keywords??

### ISSUE THREAD

**Issue by minji-o-j** [NLPCode/CBART#2]
How did you extract the keywords from the dataset(yelp, one billion words)?
I wonder if it's manual or if there's a python library or model you used.

**Comment by NLPCode** [comment]
We extract keywords from texts with a python file and we mainly consider nouns, verbs, adjectives, and adverbs.

**Comment by minji-o-j** [comment]
Could you tell me the code for this part?

**Comment by NLPCode** [comment]
I'm sorry, we didn't keep this code. Our test data are available at https://drive.google.com/drive/folders/1Dj7VX2CjSn3-g7FEYuJrT5_JWGdsAHjE?usp=sharing.
